events {}
http {
    # FastAPI Server
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/localhost+1.pem;
        ssl_certificate_key /etc/nginx/certs/localhost+1-key.pem;

        location / {
            proxy_pass http://host.docker.internal:8080;
            proxy_set_header Host $host;
            # code for websocket upgrade
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # Casdoor Server
    server {
        listen 444 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/localhost+1.pem;
        ssl_certificate_key /etc/nginx/certs/localhost+1-key.pem;

        location / {
            proxy_pass http://host.docker.internal:8000;
            proxy_set_header Host $host;
        }
    }
}